var img = {
  width : 64, height : 64, bpp : 1,
  transparent : 0,
  buffer : E.toArrayBuffer(atob("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAA/wAAAAH/gAH/gAAAAYGAAYGAAAABgYABgYAAAD///////AAA////////AADAAAAAAAMAAYAAAAAAAYABj//////xgAGf//////mAAZgAAAAAGYABmAAAAAAZgAGY/w/w/xmAAZn/n/n/mYABmYGYGYGZgAGZgZgZgZmAAZmBmBmBmYABmYGYGYGZgAGZgZgZgZmAAZn/n/n/mYABmf+f+f+ZgAGZgZgZgZmAAZmBmBmBmYABmYGYGYGZgAGZgZgZgZmAAZmBmBmBmYABmf+f+f+ZgAGZ/5/5/5mAAZgAAAAAGYABmAAAAAAZgAGf//////mAAZ//////+YABgAAAAAABgAGAAAAAAAGAB////////+AP////////8AwAAAAAAAAwDAAAAAAAADAYAAD//wAAGBwAAP//AAA4D/////////AH////////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="))
}
